### ISSUE TITLE
Water seal 

### ISSUE THREAD

**Issue by nzwaneveld** [SmartHalo-User-Group/SmartHalo-2#10]
I have received mine, but it has massive water issues! Just one ride through rain and water is inside everywhere. It’s still working, but very unreliable (touch control only partly or on its own; middle display turns on and off or dims down). I am very disappointed and I find this unacceptable! What is such a product worth, if you cannot ride your bike through a bit of rain…

Affected user:
Laurenz Strassemeyer

**Comment by nzwaneveld** [comment]
SmartHalo feedback: SmartHalo 2 is designed to be waterproof so this could be a manufacturing defect. Could you send us an email at support@smarthalo.bike with a couple of pictures and our support team will make it right. 

Solution available. Affected users can contact SH Support

**Comment by nzwaneveld** [comment]
Support is not responding to email.

**Comment by smarthalo** [comment]
Make sure to always properly close the USB port cover when outside of home. If you believe you had the port cover properly sealed and water still went in, it might be a manufacturing defect. Please contact support@smarthalo.bike
