### ISSUE TITLE
GPX only works in Compass mode

### ISSUE THREAD

**Issue by nzwaneveld** [SmartHalo-User-Group/SmartHalo-2#12]
the gpx feature is a bit useless because it works in compass mode only. Users expect that GPX also works with turn-by-turn

Peter Ziegler adds: According to the creator, GPX only works in turn-by-turn mode. That said: It doesn't work in either for me. I cannot switch to compass mode after I loaded a GPX file into the app. In turn-by-turn mode it simply doesn't work Navigation displays only senseless infos about turning around and other useless stuff.

Users:
Ulukaï FaeRahn
Peter Ziegler

**Comment by Mubaer** [comment]
Weird. According to the creator, GPX only works in turn-by-turn mode. That said: It doesn't work in either for me. I cannot switch to compass mode after I loaded a GPX file into the app. In turn-by-turn mode it simply doesn't work Navigation displays only senseless infos about turning around and other useless stuff.

**Comment by nzwaneveld** [comment]
Seems to be a few misunderstandings... 

1. this is in beta testing, therefore issues can be expected. The fix expected to released soon.
2. GPX works turn by turn. Is you go outside the route, the compass leads you back to the route... where you continue your track turn by turn. 

Changing this to an enhancement that is on the Roadmap
