### ISSUE TITLE
Lot of screen sratchs

### ISSUE THREAD

**Issue by stephanepapin** [SmartHalo-User-Group/SmartHalo-2#26]
## Description
Lot of scratchs on screen at unboxing.

## Steps To Reproduce
n#a

## Configuration
n#a

## Expected behavior

- Protected screen for shipping

## Actual behavior

- Screen not protected for shipping

## Additional context
- [Pic#01](https://drive.google.com/file/d/1qFWu6cw1Jpoj038VrTwezO0EKja5XArJ/view?usp=sharing)
- [Pic#02](https://drive.google.com/file/d/1qFuXKWjaYS2z2mSuRo5-wtsBPdfoMHRu/view?usp=sharing)
- [Pic#03](https://drive.google.com/file/d/1qQMMSRNdFunJHVO5H42HY1BtlsxHpKZZ/view?usp=sharing)
- [Pic#04](https://drive.google.com/file/d/1qYtk71CAJ3V1FMmX2WRDPUyURyPp3r9Q/view?usp=sharing)
- [Pic#05](https://drive.google.com/file/d/1qZosc4wrTRJwOUqy0OqoKaAXJ53fl3AK/view?usp=sharing)
- [Pic#06](https://drive.google.com/file/d/1qaq4e93573_XRoXtqJyksls8_JOniM7r/view?usp=sharing)
- [Pic#07](https://drive.google.com/file/d/1qcy6vkBBMvZJVu8pU0nQ-_D0rnzJV5eZ/view?usp=sharing)

**Comment by stephanepapin** [comment]
Email sended to support 15/05/2021 : still no response

**Comment by nzwaneveld** [comment]
Same issue in https://github.com/SmartHalo-User-Group/SmartHalo-2/issues/9 - I am adding you to that list for discussion with SmartHalo

**Comment by stephanepapin** [comment]
> Same issue in #9 - I am adding you to that list for discussion with SmartHalo
oh yes sorry

**Comment by stephanepapin** [comment]
Same issue in #9
