### ISSUE TITLE
touch pad seems to be non-responsive 

### ISSUE THREAD

**Issue by nzwaneveld** [SmartHalo-User-Group/SmartHalo-2#3]
User facing this issue: 
CJ Kuper

**Comment by nzwaneveld** [comment]
Smart Halo reports - May 21, 2021: If the touch seems non functioning on your device, that’s not normal behaviour indeed. Could you send a message to support@smarthalo.bike and our support team will sort you out!

Solution available. Affected users can contact SH Support

**Comment by nzwaneveld** [comment]
Support is not responding to email.

**Comment by smarthalo** [comment]
Please try rebooting the device to see if it helps. To do so, plug it into a powered USB.
