### ISSUE TITLE
How to refresh when SH2 is frozen?

### ISSUE THREAD

**Issue by stavroskool** [SmartHalo-User-Group/SmartHalo-2#30]
## Description
After trying to start a ride SM2 froze. It was fully charged but it was stuck in battery mode
Touchpad was not responding at all. Turned off/on bluetooth and nothing, deleted SM2 (from the application) and then add it again (pair again) and nothing. It started working again after connecting to usb charge.

## Steps To Reproduce
1. Random
2. Initiated when tried to started the ride
3. 30 mins ago I had made another ride, SM2 was fully operational

## Configuration
* Phone type: Nokia 8
* Phone OS version:  Android 9
* SmartHalo version: 1.17.1 

## Expected behavior

Should start recording the ride
## Actual behavior

SM2 was not operational. Alarm function seemed to get activated for a sec as well
## Additional context

Video showing the issue
https://photos.app.goo.gl/dD88hXFEC3Gy3za36

**Comment by xavierpeich** [comment]
Plug in the SmartHalo 2 in powered USB to reboot.
