### ISSUE TITLE
Switch to Discord

### ISSUE THREAD

**Issue by damnabit** [SmartHalo-User-Group/SmartHalo-2#52]
I am a developer willing to help contribute to the codebase / firmware and even just the discussions, but I will not use Facebook.

Please consider switching to a different discussion system, I might suggest Discord.

**Comment by nzwaneveld** [comment]
I agree! We have a group already on Discord. Here is the invite link: https://discord.com/invite/xee85zpkv6?fbclid=IwAR28UBFSEZDBp7q7z4wwnh178wT-HeBBddHG67S5sTXxf9nGZ0Du4r9ciAk
